[package]
name = "zk-torch-4"
version = "0.1.0"
edition = "2021"

[dependencies]
almost-goldilocks-cuda = { path = "../almost-goldilocks-cuda-rs" }
log = { version = "0.4", default-features = false }
env_logger = "0.10"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
bincode = "1.3"
once_cell = "1.15"
rand = "0.8"
rayon = "1.10"
num_cpus = "1.16"
ndarray = { version = "0.15", features = ["serde"] }
ndarray_einsum_beta = "0.7"
sha2 = "=0.10.8"
indexmap = "=2.13.0"
