// ============================================================================
// Pre-materialized M variant of the commit kernels.
//
// The default commit path regenerates M[i,j] on-the-fly via ChaCha8 every
// time the kernel runs. This file provides:
//
//   1. materialize_M_kernel — one-shot PRG fill of M[N][KAPPA][D] u64 into
//      a device buffer (computed once per seed).
//
//   2. commit_ternary_premat_kernel — clone of commit_ternary_kernel that
//      loads M_shared from the pre-materialized buffer instead of calling
//      prg_fill_column.
//
// Memory: M = N * KAPPA * D * 8 bytes = 7680 N bytes.
//   N = 2^16   →    480 MB
//   N = 2^20   →    7.5 GB
//   N = 2^22   →     30 GB
//   N = 2^27   →    960 GB  (won't fit on A100 80GB)
//
// Expected payoff: PRG (ChaCha8 at ~770 GB/s output) is replaced with an
// HBM read of M (at ~1.5 TB/s). At N where M fits, that's ~2× per-commit
// kernel speedup — the add path stays the same.
// ============================================================================

#pragma once

#include <cstdint>
#include "almost_goldilocks.cuh"
#include "ajtai_chacha8.cuh"
#include "ajtai.cuh"     // brings in ajtai::{KAPPA, D, reduce_partials_kernel, ...}

namespace ajtai {

// ---------------------------------------------------------------------------
// materialize_M_kernel: each thread fills one ChaCha8 block (= 8 u64) of
// M[j][row][block_idx*8..block_idx*8+8].
//
// Layout chosen so each (j, *, *) "column" is 15 * 64 = 960 u64s contiguous
// — matches the access pattern of commit_*_premat (one full column per j).
// ---------------------------------------------------------------------------
__global__ void materialize_M_kernel(
    const uint32_t* __restrict__ chacha_key,       // 8 u32
    uint64_t*       __restrict__ M_global,         // [N * KAPPA * D]
    uint64_t                     N
) {
    __shared__ uint32_t key_sh[8];
    if (threadIdx.x < 8) key_sh[threadIdx.x] = chacha_key[threadIdx.x];
    __syncthreads();

    uint64_t total = N * (uint64_t)KAPPA * 8;        // 8 chacha blocks per (row, j)
    uint64_t tid   = (uint64_t)blockIdx.x * blockDim.x + threadIdx.x;
    if (tid >= total) return;

    // Decompose tid into (j, row, block_idx). KAPPA*8 = 120 → fits int.
    int      tasks_per_j = KAPPA * 8;
    uint64_t j           = tid / (uint64_t)tasks_per_j;
    int      rem         = (int)(tid % (uint64_t)tasks_per_j);
    int      row         = rem / 8;
    int      block_idx   = rem & 7;

    uint64_t buf[8];
    prg_ring_block_chacha8(key_sh, (uint32_t)row, j, (uint32_t)block_idx, buf);

    // M_global[j][row][block_idx*8 .. block_idx*8 + 8].
    uint64_t base = j * (uint64_t)(KAPPA * D) + (uint64_t)row * D + block_idx * 8;
    #pragma unroll
    for (int k = 0; k < 8; k++) {
        M_global[base + k] = buf[k];
    }
}

inline cudaError_t materialize_M_run(
    const uint32_t* d_chacha_key,
    uint64_t*       d_M_global,
    uint64_t        N,
    cudaStream_t    stream = 0
) {
    uint64_t total = N * (uint64_t)KAPPA * 8;
    int      block = 256;
    uint64_t grid64 = (total + block - 1) / block;
    int      grid   = (int)grid64;
    materialize_M_kernel<<<grid, block, 0, stream>>>(d_chacha_key, d_M_global, N);
    return cudaGetLastError();
}

// ---------------------------------------------------------------------------
// commit_ternary_premat_kernel: same as commit_ternary_kernel except M_sh
// is loaded from M_global instead of generated by prg_fill_column.
//
// Per j: 15 * 64 = 960 u64s (7680 B) are read cooperatively into M_sh by
// the 832 threads (1.15 u64 each on average).
// ---------------------------------------------------------------------------
template <int CHUNK>
__global__ void
__launch_bounds__(SPLIT_K * D, 1)
commit_ternary_premat_kernel(
    const uint64_t* __restrict__ M_global,         // [N_ring * KAPPA * D]
    const uint64_t* __restrict__ pos_packed,       // [SPLIT_K * N_ring]
    const uint64_t* __restrict__ neg_packed,       // [SPLIT_K * N_ring]
    uint64_t*       __restrict__ partial,          // [num_chunks_j][SPLIT_K][KAPPA][D]
    uint64_t                     N_ring
) {
    int chunk = blockIdx.x;
    int t     = threadIdx.x;
    int b     = t / D;
    int r     = t & (D - 1);

    __shared__ uint64_t M_sh[KAPPA * D];           // 7680 bytes
    __shared__ uint64_t pos_sh[SPLIT_K];
    __shared__ uint64_t neg_sh[SPLIT_K];

    uint64_t acc[KAPPA];
    #pragma unroll
    for (int i = 0; i < KAPPA; i++) acc[i] = 0;

    uint64_t j_lo = (uint64_t)chunk * CHUNK;
    uint64_t j_hi = (j_lo + CHUNK < N_ring) ? (j_lo + CHUNK) : N_ring;

    __syncthreads();

    for (uint64_t j = j_lo; j < j_hi; j++) {

        // (a) Load 13 pos + 13 neg bitmasks for this j.
        if (t < SPLIT_K) {
            pos_sh[t] = pos_packed[(uint64_t)t * N_ring + j];
            neg_sh[t] = neg_packed[(uint64_t)t * N_ring + j];
        }

        // (b) Cooperatively load M[j][*][*] from global → M_sh.
        const uint64_t col_base = j * (uint64_t)(KAPPA * D);
        #pragma unroll 1
        for (int idx = t; idx < KAPPA * D; idx += (int)blockDim.x) {
            M_sh[idx] = M_global[col_base + (uint64_t)idx];
        }
        __syncthreads();

        // (c) Additive pass for pos bits.
        uint64_t mp = pos_sh[b];
        while (mp) {
            int  ell  = __ffsll((long long)mp) - 1;
            mp       &= mp - 1;
            int  idx_  = r - ell;
            bool wrap  = idx_ < 0;
            idx_      += wrap ? D : 0;

            #pragma unroll
            for (int i = 0; i < KAPPA; i++) {
                uint64_t v = M_sh[i * D + idx_];
                acc[i] = add_signed(acc[i], v, wrap);
            }
        }

        // (d) Subtractive pass for neg bits.
        uint64_t mn = neg_sh[b];
        while (mn) {
            int  ell  = __ffsll((long long)mn) - 1;
            mn       &= mn - 1;
            int  idx_  = r - ell;
            bool wrap  = idx_ < 0;
            idx_      += wrap ? D : 0;

            #pragma unroll
            for (int i = 0; i < KAPPA; i++) {
                uint64_t v = M_sh[i * D + idx_];
                acc[i] = add_signed(acc[i], v, !wrap);
            }
        }
        __syncthreads();
    }

    uint64_t base = ((uint64_t)chunk * SPLIT_K + b) * (KAPPA * D) + r;
    #pragma unroll
    for (int i = 0; i < KAPPA; i++) {
        partial[base + i * D] = acc[i];
    }
}

template <int CHUNK>
inline cudaError_t commit_ternary_premat_run(
    const uint64_t* d_M_global,
    const uint64_t* d_pos_packed,
    const uint64_t* d_neg_packed,
    uint64_t        N_ring,
    uint64_t*       d_out,                          // [SPLIT_K][KAPPA][D]
    cudaStream_t    stream = 0
) {
    static_assert(SPLIT_K * D <= 1024, "blockDim exceeds 1024");

    uint64_t num_chunks    = (N_ring + CHUNK - 1) / CHUNK;
    uint64_t partial_count = num_chunks * (uint64_t)SPLIT_K * KAPPA * D;

    uint64_t* d_partial = nullptr;
    cudaError_t err = cudaMallocAsync(&d_partial, partial_count * sizeof(uint64_t), stream);
    if (err != cudaSuccess) return err;

    dim3 grid1((unsigned)num_chunks);
    dim3 block1((unsigned)(SPLIT_K * D));
    commit_ternary_premat_kernel<CHUNK><<<grid1, block1, 0, stream>>>(
        d_M_global, d_pos_packed, d_neg_packed, d_partial, N_ring
    );

    dim3 grid2((unsigned)SPLIT_K, (unsigned)KAPPA, (unsigned)D);
    int  block2 = 256;
    size_t shared = (size_t)block2 * sizeof(uint64_t);
    reduce_partials_kernel<<<grid2, block2, shared, stream>>>(
        d_partial, d_out, SPLIT_K, num_chunks
    );

    cudaError_t free_err = cudaFreeAsync(d_partial, stream);
    if (free_err != cudaSuccess) return free_err;
    return cudaGetLastError();
}

} // namespace ajtai
